# Generated by Django 5.1.7 on 2025-04-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, default='sem marca', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vendas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
