# Generated by Django 5.1.7 on 2025-04-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_product_created_at_remove_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], max_length=20)),
                ('validade', models.DateField(blank=True, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
