# Generated by Django 5.1.7 on 2025-04-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_produto_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='status',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='validade',
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='Sem Marca', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='vendas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
