# Generated by Django 5.1.7 on 2025-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_produto_ativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='logdeacao',
            name='tipo',
            field=models.CharField(default='info', max_length=20),
        ),
    ]
