# Generated by Django 5.1.7 on 2025-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_delete_product_logdeacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdeacao',
            name='valor_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdeacao',
            name='valor_novo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
