# Generated by Django 5.1.7 on 2025-04-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_produto_status_remove_produto_validade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='vendas',
            field=models.IntegerField(default=0),
        ),
    ]
