# Generated by Django 5.1.7 on 2025-05-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_logdeacao_valor_anterior_logdeacao_valor_novo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdeacao',
            name='tipo',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
