# Generated by Django 5.1.7 on 2025-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_produto_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
