# Generated by Django 5.1.7 on 2025-05-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_logdeacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendedor', 'vendedor'), ('gerente', 'Gerente')], default='vendedor', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
