# Generated by Django 5.1.7 on 2025-05-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_produto_data_atualizacao_produto_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('pc', 'Peça'), ('box', 'Caixa'), ('pcte', 'Pacote'), ('rol', 'Rolo'), ('par', 'Par'), ('kit', 'Kit'), ('cx', 'Caixa'), ('saco', 'Saco'), ('bandeja', 'Bandeja'), ('lata', 'Lata'), ('frasco', 'Frasco'), ('garrafa', 'Garrafa'), ('pacote', 'Pacote')], default='un', max_length=10),
        ),
    ]
