# Generated by Django 5.1.7 on 2025-05-10 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_entradaestoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaestoque',
            name='motivo',
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produto'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='tipo',
            field=models.CharField(blank=True, choices=[('compra', 'Compra'), ('ajuste', 'Ajuste'), ('devolucao', 'Devolução de Cliente'), ('transferencia', 'Transferência'), ('correcao', 'Correção de Estoque'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
