# Generated by Django 5.1.7 on 2025-05-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_entradaestoque_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('ajuste', 'Ajuste'), ('devolucao', 'Devolução de Cliente'), ('transferencia', 'Transferência'), ('correcao', 'Correção de Estoque'), ('outro', 'Outro')], default='compra', max_length=50),
        ),
    ]
