# Generated by Django 5.1.7 on 2025-05-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_entradaestoque_preco_unitario_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='validade',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
