# Generated by Django 5.1.7 on 2025-05-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_remove_produto_validade_movimentacaoestoque_validade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='vendas',
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='tipo_personalizado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Estoque mínimo antes de alerta'),
        ),
        migrations.DeleteModel(
            name='MovimentacaoEstoque',
        ),
    ]
