# Generated by Django 5.1.7 on 2025-05-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_remove_produto_vendas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaestoque',
            old_name='data',
            new_name='data_entrada',
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='validade',
            field=models.DateField(),
        ),
    ]
