# Generated by Django 5.1.7 on 2025-05-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stock', '0020_alter_movimentacao_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsaida',
            name='saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_saida', to='stock.saidaestoque'),
        ),
        migrations.RenameField(
            model_name='saidaestoque',
            old_name='preco_unitario',
            new_name='valor_total',
        ),
        migrations.RenameField(
            model_name='saidaestoque',
            old_name='preco_unitario_currency',
            new_name='valor_total_currency',
        ),
        migrations.RemoveField(
            model_name='saidaestoque',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='saidaestoque',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='itens',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Saida',
        ),
    ]
