# Generated by Django 5.1.7 on 2025-05-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_saidaestoque_tipo_itementrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itementrada',
            old_name='preco_unitario',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='itementrada',
            old_name='preco_unitario_currency',
            new_name='valor_currency',
        ),
        migrations.RenameField(
            model_name='itemsaida',
            old_name='preco_unitario',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='itemsaida',
            old_name='preco_unitario_currency',
            new_name='valor_currency',
        ),
    ]
