# Generated by Django 5.1.7 on 2025-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_rename_preco_unitario_itementrada_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdeacao',
            name='tipo',
            field=models.CharField(default='light', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
