# Generated by Django 5.1.7 on 2025-05-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_alter_logdeacao_tipo_alter_produto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente')], default='vendedor', max_length=50),
        ),
    ]
